image: golang:1.18.4-bullseye

before_script:
- echo "machine gitlab.com login gitlab-ci-token password ${CI_JOB_TOKEN}" > ~/.netrc

build:
  script:
  - make check build
  - |
    if [ -n "${CI_COMMIT_TAG}" ] ; then
      curl --silent --show-error --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file epicctl "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/epicctl/${CI_COMMIT_TAG}/epicctl"
      curl --silent --show-error --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file scripts/scan-logs "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/epicctl/${CI_COMMIT_TAG}/scan-logs"
    fi

  artifacts:
    paths:
    - epicctl
    - scripts/*
