image: golang:1.17.2-buster

before_script:
- echo "machine gitlab.com login gitlab-ci-token password ${CI_JOB_TOKEN}" > ~/.netrc

build:
  script:
  - make check build

  artifacts:
    paths:
    - epicctl
